######################### default configuration ###############################
baseURL = "/"
title = "Biztrox"
theme = "biztrox-hugo"
# post pagination
paginate = "6"
# post excerpt
summaryLength = "10"
# google analytics
googleAnalytics = "" # example : UA-123-45
# disqus short name
disqusShortname = "themefisher-template" # get your shortname form here : https://disqus.com
# disable language

# https://gohugo.io/content-management/multilingual/
defaultContentLanguage = 'de'

disableLanguages = ["fr", "en"] # desable language from here

############################# Outputs ##############################
[outputs]
home = ["HTML", "RSS"]

[markup.goldmark.renderer]
unsafe= true

############################# Plugins ##############################

# CSS Plugins
[[params.plugins.css]]
link = "https://fonts.googleapis.com/css2?family=Open+Sans&family=Poppins:wght@400;500&display=swap"
attributes = ""

[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
attributes = "media='screen'"

[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
attributes = "media='screen'"

[[params.plugins.css]]
link = "plugins/magnific-popup/magnific-popup.css"
attributes = "media='screen'"

[[params.plugins.css]]
link = "plugins/slick/slick.css"
attributes = ""

[[params.plugins.css]]
link = "plugins/slick/slick-theme.css"
attributes = ""

[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"
attributes = ""

[[params.plugins.css]]
link = "plugins/animate/animate.css"
attributes = ""


# JS Plugins
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
attributes = ""

[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
attributes = ""

[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
attributes = ""

[[params.plugins.js]]
link = "plugins/magnific-popup/magnific-popup.min.js"
attributes = ""

[[params.plugins.js]]
link = "plugins/filterizr/jquery.filterizr.min.js"
attributes = ""

[[params.plugins.js]]
link = "plugins/google-map/gmap.js"
attributes = "async"

########################### default parameters #################################
[params]
favicon = "images/favicon.png"
logo = "images/logo_bauer.png"
logo_width = "110px"
logo_footer = "images/logo-footer.png"
logo_footer_width = "180px"
mail = "stefan@swadok.de"
mobile = "1234565523"
# Meta data
description = "this is meta description"
author = "themefisher"
# contact form
contact_form_action = "#" # contact form works with https://formspree.io or https://formsubmit.co
# custom script
custom_script = ""

# nav Button
[params.nav_button]
enable = true
link = "autor/#kontakt"

# preloader
[params.preloader]
enable = false
preloader = "images/preloader.gif"

# Subscription
[params.subscription]
enable = false
# subscribe
title = "Subscribe Us"
content = "Lorem ipsum dolor sit amet, consect etur adipisicing. elit sed do eiusmod."
# mailchimp subsciption
mailchimp_form_action = "https://gmail.us4.list-manage.com/subscribe/post?u=463ee871f45d2d93748e77cad&amp;id=a0a2c6d074" # replace this url with yours
mailchimp_form_name = "b_463ee871f45d2d93748e77cad_a0a2c6d074" # replace this code with yours

# google map
[params.gmap]
enable = true
gmap_api = "AIzaSyCcABaamniA6OL5YvYSpB3pFMNrXwXnLwU"
map_latitude = "51.5223477"
map_longitude = "-0.1622023"
map_marker = "images/marker.png"


########################### social icon #####################################

[[params.social]]
icon = "ti-email" # themify icon pack : https://themify.me/themify-icons
link = "mailto:stefan@swadok.de"

[[params.social]]
icon = "ti-angle-double-right" # themify icon pack : https://themify.me/themify-icons
link = "https://xing.to/szr"

[[params.social]]
icon = "ti-twitter" # themify icon pack : https://themify.me/themify-icons
link = "https://twitter.com/StefanZoerner"



################################### German language #####################################
[Languages.de]
languageName = "De"
languageCode = "de-de"
contentDir = "content"
weight = 1
home = "Start"
# footer content
footer_content = "Fragen? Anregungen? Wünsche?<br>Nur nicht zögern.<br> Sondern gern Kontakt aufnehmen ..."
# copyright
copyright = "Copyright &copy; 2021 by Stefan Zörner"

###################### German navigation ####################

# main menu
[[Languages.de.menu.main]]
name = "Start"
url = "/"
weight = 1

[[Languages.de.menu.main]]
name = "Buch"
url = "buch/"
weight = 2

[[Languages.de.menu.main]]
name = "Autor"
url = "autor/"
weight = 3

[[Languages.de.menu.main]]
name = "Features"
url = "feature/"
weight = 4

[[Languages.de.menu.main]]
name = "Beispiele"
url = "beispiel/"
weight = 5

[[Languages.de.menu.main]]
name = "Downloads"
url = "#"
weight = 6


# footer menu
[[Languages.de.menu.footer]]
name = "Impressum"
url = "/impressum/"
weight = 1

